application:
  subdomain: readur
  oidc_redirect_path: /auth/callback
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://readur:8000/

services:
  readur:
    # ghcr.io/readur/readur:2.6.2
    image: registry.lazycat.cloud/czyt/readur/readur:b667b11ff4ffe27a
    environment:
      #- DATABASE_URL=postgresql://readur:readur@postgres/readur
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=readur
      - POSTGRES_USER=readur
      - POSTGRES_PASSWORD={{ stable_secret "db_password" }}
      - SERVER_ADDRESS=0.0.0.0:8000
        # Security
      - JWT_SECRET={{ stable_secret "jwt$secret"  }}
        # File paths
      - UPLOAD_PATH=/app/uploads
      - WATCH_FOLDER=/app/watch

        # OCR configuration
        # # Available languages (partial list):
        # eng - English
        # deu - German (Deutsch)
        # fra - French (Français)
        # spa - Spanish (Español)
        # ita - Italian (Italiano)
        # por - Portuguese
        # rus - Russian
        # chi_sim - Chinese Simplified
        # jpn - Japanese
        # ara - Arabic
      - OCR_LANGUAGE=eng+chi_sim
      - CONCURRENT_OCR_JOBS=4
      - OCR_TIMEOUT_SECONDS=300
      - MAX_FILE_SIZE_MB=50
        # Performance
      - MEMORY_LIMIT_MB=512
      - CPU_PRIORITY=normal

        # File watching
      - ALLOWED_FILE_TYPES=pdf,txt,doc,docx,png,jpg,jpeg
      - WATCH_INTERVAL_SECONDS=30
      - FILE_STABILITY_CHECK_MS=1000
      - MAX_FILE_AGE_HOURS=24

    binds:
      - /lzcapp/var/upload:/app/uploads
      - /lzcapp/var/watch:/app/watch
    depends_on:
      - postgres
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:8000/api/health
      start_period: 40s

  postgres:
    # docker.io/library/postgres:17-alpine
    image: registry.lazycat.cloud/czyt/library/postgres:bb84b585f0ed5342
    environment:
      - POSTGRES_USER=readur
      - POSTGRES_PASSWORD={{ stable_secret "db_password" }}
      - POSTGRES_DB=readur
    binds:
      - /lzcapp/var/data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U readur
      start_period: 90s
